### ISSUE TITLE
js parsing error on deploy

### ISSUE THREAD

**Issue by david-saeger** [nasa-gcn/americana-stack#48]
# Current behavior
When I try to deploy I get a JS parsing error 

```
 Error: JS parsing error(s), could not automatically determine dependencies
File: /Users/xxx/projects/xxx/build/server/index.cjs
TypeError: dep.includes is not a function
    at /Users/xxx/projects/pvq-remix/node_modules/@architect/hydrate/src/actions/autoinstall/node/find-lambda-deps.js:69:13
    at Array.map (<anonymous>)
    at findLambdaDeps (/Users/xxx/projects/xxx/node_modules/@architect/hydrate/src/actions/autoinstall/node/find-lambda-deps.js:68:15)
    at /Users/xxx/projects/pvq-remix/node_modules/@architect/hydrate/src/actions/autoinstall/node/get-lambda-deps.js:23:22
    at Array.forEach (<anonymous>)
    at getDirDeps (/Users/xxx/projects/pvq-remix/node_modules/@architect/hydrate/src/actions/autoinstall/node/get-lambda-deps.js:21:9)
    at /Users/xxx/projects/xxx/node_modules/@architect/hydrate/src/actions/autoinstall/node/index.js:76:20
    at Array.forEach (<anonymous>)
    at treeshakeNode (/Users/xxx/projects/pvq-remix/node_modules/@architect/hydrate/src/actions/autoinstall/node/index.js:67:12)
    at Object.autoinstaller [as autoinstall] (/Users/xxx/projects/pvq-remix/node_modules/@architect/hydrate/src/actions/autoinstall/index.js:25:23)
```

# Expected behavior
I expect to deploy without this error
# Steps to reproduce
`npx arc deploy`
# Environment
MacBook Pro Apple M1 Pro

**Comment by lpsinger** [comment]
@dakota002, would you please update this repository to bring it in line with versions of dependencies in https://github.com/nasa-gcn/gcn.nasa.gov?
